[package]
name = "hash"
version = "0.1.0"
authors = ["Robin Salen <salenrobin@gmail.com>"]
edition = "2018"

[dependencies]
stark-curve = { git = "https://github.com/ToposWare/stark-curve.git", branch = "main", default-features = false }
